# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30447c5a6c1ccfa083b67e10e811437a55bb06488516af133bf589692fae72e3e348867debd573fcb03d37435681e6796afe0f00bc94032ceb130d0cf3b0f711

test:
  secret_key_base: ac5f2645895001099bfd6ffb87efc2be4240d10420d5ad35e15a45dbe1cb7824a2e63cfe8ae79dfca172b7e53e753c99bdafd617cf088981d967a720f62db6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
